Задание 1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np
# import matplotlib.pyplot as plt

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

Задание 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
c = list(set([len(a) // i for i in range(1, len(a))]))

for i in c:
    print(a.reshape(i ,len(a) // i))
    print()

[[12 13 14 15 16 17 18 19 20 21 22 23]]

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]



Задание 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
c = list(set([len(a) // i for i in range(1, len(a))]))

for i in c:
    if c.index(i) < 3:
        print(a.reshape(i , -1))
        print()
    else:
        print(a.reshape(-1 , i))
        print()

[[12 13 14 15 16 17 18 19 20 21 22 23]]

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13 14 15 16 17 18 19 20 21 22 23]]



Задание 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет

Задание 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [5]:
a_1 = np.random.randn(3, 4)
a_2 = a_1.flatten()

a_1.size == a_2.size

True

Задание 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [6]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Задание 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [7]:
b = np.arange(20, 0, -2)
b.reshape(1, 10)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Задание 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [8]:
b = np.ones((3, 2))
a = np.zeros((b.shape[0] + 1, b.shape[1] - 1))

v = (np.hstack((a.flatten(), b.flatten()))).reshape(2, -1)

print(v)
print(f'\nПараметр size равен {v.size}')

[[0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Параметр size равен 10


Задание 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [9]:
a = np.arange(12)
a = a.reshape(4, -1)
At = a.T

B = np.dot(a, At)

print(f'Матрица b имеет размер {B.shape}')
print(B)

Матрица b имеет размер (4, 4)
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


 Задание 10
 
 Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [10]:
np.random.seed(42)
a = np.random.randint(0, 100, 3)
a

array([51, 92, 14])

Задание 11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [11]:
np.random.seed(42)

a = np.random.randint(0, 16, 16)

print(a)

[ 6  3 12 14 10  7 12  4  6  9  2  6 10 10  7  4]


Задание 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [12]:
num = int(pow((a.size), 0.5))

C = a.reshape((num, -1))
B = a
D = np.add(B.reshape(C.shape), C.dot(10))
D_inv = np.linalg.inv(D)

print(f'Определитель матрицы D равен {np.linalg.det(D):.3}')
print(f'Ранг матрицы D равен {np.linalg.matrix_rank(D)}')
print(f'Матрица обратная В\n\n{D_inv}')

Определитель матрицы D равен 9.84e+06
Ранг матрицы D равен 4
Матрица обратная В

[[ 0.03003247 -0.10660173 -0.10687229  0.16179654]
 [-0.02435065  0.07251082  0.0784632  -0.10497835]
 [-0.01461039  0.06168831  0.04707792 -0.08116883]
 [ 0.01136364 -0.02272727 -0.01136364  0.02272727]]


Задание 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [13]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1

E = np.where(D_inv > 0, B.reshape(4, 4), C)
E

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])